name: Check Vars and Env
#checking the condition
on:
  push:
env:
    test: ${{ vars.HELLO }}
    test2: ${{ vars.HELLO }}
jobs:
  test-vars:
    runs-on: 'ubuntu-22.04'
    steps:
        - name: Say hello 
          run: |
            echo "${{ env.test }}"
            echo "${{ vars.test2 }}"
            echo "${{ vars.HELLO}}"